### ISSUE TITLE
New model repo in HF

### ISSUE THREAD

**Issue by PrithivirajDamodaran** [synacktraa/swiftrank#2]
@synacktraa - Here is a HF repo of flashrank int8 models, https://huggingface.co/prithivida/flashrank 

Feel free to use it. and it is covered under cc-by-sa-4.0 license for source attribution.

**Comment by synacktraa** [comment]
Thanks for hosting the models on HuggingFace.

**Comment by PrithivirajDamodaran** [comment]
Citation instructions are available in flashrank repo. Add the same ideally before your credits. 

The title announcement should reflect swiftrank reuses flashrank int8 models now from a HF repo.

**Comment by synacktraa** [comment]
Ok
